name: Rust CI
on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      
      - name: Rust test
        run: cargo test --verbose
      - name: Upload test logs
        run: cargo test --verbose &> test.log
      - name: Upload test logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test.log

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      
      - name: Rust build
        run: cargo build --release --verbose
      - name: Upload build logs
        run: cargo build --release --verbose &> build.log
      - name: Upload build logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml

  show_logs:
    runs-on: ubuntu-latest
    needs: [test, build] 
    steps:
      - name: Download and show build logs
        uses: actions/download-artifact@v4
        with:
          name: build-logs

      - name: Download and show test logs
        uses: actions/download-artifact@v4
        with:
          name: test-logs

      - name: Display logs
        run: |
          echo "===== Build Logs ====="
          cat build.log
          echo "===== Test Logs ====="
          cat test.log

  reports:
    needs: [test, build, deploy]
    if: failure()  
    runs-on: ubuntu-latest
    steps:
      - name: Output logs
        run: |
          echo "Algo ha fallado"
          echo "${{ toJSON(github)}}"
