name: Deploy Rust App
on: 
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      
      - name: Rust test
        if: success()
        run: cargo test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          sudo apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      
      - name: Rust build
        if: success()
        run: cargo build --release
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
  reports:
    needs: [test, build, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output logs
        run: |
          echo "Algo ha fallado"
          echo "${{ toJSON(github)}}"